import localFont from "next/font/local";
import { Libre_Franklin } from "next/font/google"
import "./globals.css";

import Navigation from "./components/navigation"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const libreFranklin = Libre_Franklin({
    weight: "100",
    subsets: ["latin"]
})

export const metadata = {
  title: "Icebreakers!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${libreFranklin.className} antialiased`}
      >
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
